# Generated by Django 3.0.2 on 2020-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_io', models.BooleanField()),
                ('ac_city', models.CharField(max_length=100)),
                ('ac_temp', models.CharField(max_length=100)),
            ],
        ),
    ]
