# Generated by Django 3.0.2 on 2020-02-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='appliace',
            new_name='appliance',
        ),
    ]
