# Generated by Django 3.0.2 on 2020-02-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20200203_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='stop_time',
            new_name='stop',
        ),
    ]
