# Generated by Django 3.0.2 on 2020-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20200203_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stop',
            field=models.CharField(max_length=5),
        ),
    ]
