# Generated by Django 3.0.2 on 2020-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20200204_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usage',
            name='stop',
            field=models.CharField(max_length=100),
        ),
    ]
