# Generated by Django 3.0.2 on 2020-02-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appliances_a_io'),
        ('iot', '0007_usage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_io', models.BooleanField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Appliances')),
            ],
        ),
    ]
