# Generated by Django 3.0.2 on 2020-02-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200207_0025'),
        ('iot', '0008_iomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_lockout', models.BooleanField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Appliances')),
            ],
        ),
    ]
