# Generated by Django 3.0.2 on 2020-02-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_remove_tubelight_a_flux'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='a_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
