# Generated by Django 3.0.2 on 2020-02-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200131_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_rating', models.CharField(max_length=100)),
                ('a_kwh', models.CharField(max_length=100)),
                ('a_priority', models.CharField(max_length=100)),
                ('a_control', models.BooleanField()),
                ('a_lockout', models.BooleanField()),
            ],
        ),
    ]
