# Generated by Django 3.0.2 on 2020-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appliances'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.IntegerField()),
                ('appliances', models.ManyToManyField(to='main.Appliances')),
            ],
        ),
    ]
