# Generated by Django 3.0.2 on 2020-02-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='a_io',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
