# Generated by Django 3.0.2 on 2020-02-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appliances_a_io'),
    ]

    operations = [
        migrations.CreateModel(
            name='kwhUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=50)),
                ('stop', models.CharField(max_length=50)),
                ('kwh', models.CharField(max_length=100)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Appliances')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomPlan',
        ),
    ]
