# Generated by Django 3.0.2 on 2020-02-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200207_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwhusage',
            name='kwh',
        ),
    ]
