# Generated by Django 3.0.2 on 2020-02-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_kwhusage_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appliances',
            name='a_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
            preserve_default=False,
        ),
    ]
