# Generated by Django 3.0.2 on 2020-02-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200207_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliances',
            name='a_control',
        ),
        migrations.RemoveField(
            model_name='appliances',
            name='a_rating',
        ),
    ]
