# Generated by Django 3.0.2 on 2020-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200208_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='u',
            name='saved',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
